
cloud:
  group: DCache 
  name: ConfigServer
  logo: logo/logo.png
  version: latest
  changelist: Changelist.md
  lang: cpp
  description: >-
    DCache is a distributed cache based on tars. Configserver mainly provides an interface to the cache module to facilitate the cache module to obtain relevant configuration
  description_cn:
    DCache是一套基于tars的分布式缓存, ConfigServer主要给Cache模块提供接口, 以方便Cache模块获取相关的配置
  collaborators:
    - ruanshudong@qq.com
  repository: https://github.com/Tencent/DCache.git
  readme: README-EN.md
  readme_cn: README.md
  protocols: []
  assets: 
    - docs
    - docs_en
app: DCache
server: ConfigServer
template: tars.cpp
profile: ''
servants:
  - name: ConfigObj
    port: 11772
    isTars: true
    isTcp: true
    thread: 5
    capacity: 100000
    connection: 100000
    timeout: 60000
replicas: 1
hostNetwork: false
hostIPC: false
hostPorts: []
repo:
  id:
  image: tarscloud/dcache.configserver
  secret: cloud-market-secret
config:
  - name: ConfigServer.conf
    content: |
      <Main>
          <DB>
              dbhost= dcache_host
              dbpass= dcache_pass
              dbuser= dcache_user
              dbname= db_dcache_relation
              charset=utf8mb4
              dbport= dcache_port
          </DB>
      </Main>